CREATE TYPE terms_status AS ENUM ('pending', 'agreed');

CREATE TABLE finance_terms (
    id UUID PRIMARY KEY,
    status terms_status NOT NULL DEFAULT 'pending',
    due_date DATE NOT NULL,
    total_downpayment NUMERIC(12, 2) NOT NULL,
    agreed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT terms_downpayment_nonnegative CHECK (total_downpayment >= 0),
    CONSTRAINT terms_agreement_consistent CHECK (
        (status = 'pending' AND agreed_at IS NULL)
        OR (status = 'agreed' AND agreed_at IS NOT NULL)
    )
);

CREATE INDEX ix_finance_terms_due_date ON finance_terms (due_date);
CREATE INDEX ix_finance_terms_total_downpayment ON finance_terms (total_downpayment);

CREATE TABLE policies (
    id UUID PRIMARY KEY,
    finance_terms_id UUID NOT NULL REFERENCES finance_terms (id) ON DELETE CASCADE,
    insured_name VARCHAR(200) NOT NULL,
    name VARCHAR(200) NOT NULL,
    premium NUMERIC(12, 2) NOT NULL,
    tax_fee NUMERIC(12, 2) NOT NULL,
    downpayment NUMERIC(12, 2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT policy_name_nonblank CHECK (length(trim(name)) > 0),
    CONSTRAINT policy_insured_name_nonblank CHECK (length(trim(insured_name)) > 0),
    CONSTRAINT policy_amounts_valid CHECK (
        premium > 0 AND tax_fee >= 0 AND downpayment >= 0
    )
);

CREATE INDEX ix_policies_finance_terms_id ON policies (finance_terms_id);

CREATE TABLE audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- No foreign key: rejected attempts may refer to nonexistent terms.
    finance_terms_id UUID NOT NULL,
    action VARCHAR(20) NOT NULL,
    outcome VARCHAR(20) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    request_id VARCHAR(200),
    details JSONB NOT NULL,
    CONSTRAINT audit_action_valid CHECK (action IN ('create', 'agree')),
    CONSTRAINT audit_outcome_valid CHECK (outcome IN ('succeeded', 'unchanged', 'rejected'))
);

CREATE INDEX ix_audit_events_terms_id ON audit_events (finance_terms_id, id);
